import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { blake3Hash, toHex, utf8 } from './hash';
import { canonicalManifestBytes, type Manifest, manifestHashHex } from './manifest';

interface Fixture {
  manifestBytesHex: string;
  manifestHashHex: string;
  workdirRootHashHex: string;
}

// The fixtures are generated by the Rust engine (cargo run -p reeg-snapshot --example
// conformance[/_nonascii]). Reading them here keeps a single source of truth: if the TS
// encoder ever stops byte-matching the engine, the relevant test fails.
function loadFixture(name: string): Fixture {
  return JSON.parse(
    readFileSync(fileURLToPath(new URL(`../fixtures/${name}`, import.meta.url)), 'utf8'),
  );
}

const fixture = loadFixture('manifest.json') as Fixture & { input: { workdirRootSeed: string } };

describe('manifest conformance with the Rust engine', () => {
  const rootHex = toHex(blake3Hash(utf8(fixture.input.workdirRootSeed)));

  it('reproduces the engine workdir root hash (proves BLAKE3 parity)', () => {
    expect(rootHex).toBe(fixture.workdirRootHashHex);
  });

  it('reproduces the engine canonical bytes and manifest hash exactly', () => {
    // Inputs are intentionally unsorted and contain a duplicate tool; the encoder must
    // normalize them into the same canonical bytes the engine produced.
    const manifest: Manifest = {
      schemaVersion: 1,
      packages: [
        { name: 'rust', version: '1.95' },
        { name: 'node', version: '24' },
      ],
      env: { PATH: '/usr/bin', LANG: 'en' },
      tools: ['ripgrep', 'git', 'git'],
      memoryPointer: null,
      workdirRootHashHex: rootHex,
    };

    expect(toHex(canonicalManifestBytes(manifest))).toBe(fixture.manifestBytesHex);
    expect(manifestHashHex(manifest)).toBe(fixture.manifestHashHex);
  });
});

describe('manifest conformance with non-ASCII ordering', () => {
  // U+E000 sorts before U+10000 by UTF-8 bytes but after it by UTF-16 code units. A naive JS
  // sort would order these the wrong way; this proves compareUtf8 reproduces Rust's order.
  const LOW = String.fromCodePoint(0xe000);
  const HIGH = String.fromCodePoint(0x10000);
  const nonAscii = loadFixture('manifest-nonascii.json');

  it('reproduces the engine canonical bytes for non-ASCII keys, packages, and tools', () => {
    const rootHex = toHex(blake3Hash(utf8('reeg-nonascii-root')));
    const manifest: Manifest = {
      schemaVersion: 1,
      // Deliberately listed HIGH-first so the encoder must sort them into UTF-8 order.
      packages: [
        { name: HIGH, version: '1' },
        { name: LOW, version: '1' },
      ],
      env: { [LOW]: 'l', [HIGH]: 'h' },
      tools: [HIGH, LOW],
      memoryPointer: null,
      workdirRootHashHex: rootHex,
    };

    expect(rootHex).toBe(nonAscii.workdirRootHashHex);
    expect(toHex(canonicalManifestBytes(manifest))).toBe(nonAscii.manifestBytesHex);
    expect(manifestHashHex(manifest)).toBe(nonAscii.manifestHashHex);
  });
});
